# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='qualification',
            field=models.CharField(choices=[(b'B', b'Btech'), (b'M', b'Mca')], default=b'btech', max_length=6),
        ),
    ]
